FROM crsycdivaasandbox.azurecr.io/rubyrhod/x86_64_env:latest

COPY rubyrhod_ws rubyrhod_ws

WORKDIR /rubyrhod_ws


RUN catkin profile set arm64_platform_x86_machine && \
    catkin clean -y
    
RUN /bin/bash -c ". /opt/ros/noetic/setup.bash && catkin build"

RUN echo "source /rubyrhod_ws/devel/setup.bash" >> ~/.bashrc

# ROS entrypoint 
ENTRYPOINT [ "/ros_entrypoint.sh" ]

# Startup command
CMD "/bin/bash"