sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /depth_to_rgb/image_raw
    queue_size: 1
    near_clipping_plane_distance: 0.2
    far_clipping_plane_distance: 0.8
    shadow_threshold: 0.2
    padding_scale: 4.0
    padding_offset: 0.06
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud
    